### ISSUE TITLE
Preparar o evento

### ISSUE THREAD

**Issue by augusto-herrmann** [economiagovbr/opendataday2022#2]
Realizar os preparativos para o Open Data Day da SEGES, em 5 de março de 2022.

Checklist:
* [x] definir os conjuntos de dados que serão utilizados
* [x] convidar as pessoas que irão fazer apresentações
* [x] #1
* [x] escolher e testar as ferramentas de transmissão (*streaming*)
 * OBS Studio
 * Jisti Meet
 * PeerTube
* [x] escolher a ferramenta para receber comentários / feedback – PeerTube
* [ ] preparar os notebooks que serão utilizados nas oficinas
* [x] #3 
* [x] incluir o evento no mapa do site opendataday.org
* [x] #4

**Comment by augusto-herrmann** [comment]
@lucasbenevides, a página do evento já está [feita](https://economiagovbr.github.io/opendataday2022/). Se estiver de acordo, já posso acrescentar no mapa do site do opendataday.org.

**Comment by lucasbenevides** [comment]
Tá, estou de acordo e os participantes também. Podemos considerar fechado o evento. Mas temos que colocar os links de assistirem o streaming

**Comment by augusto-herrmann** [comment]
Estamos no mapa!

![mapa-opendataday-2022](https://user-images.githubusercontent.com/1058414/156821048-f1aaccdd-e5d6-44d9-b213-1e698576dda9.png)

**Comment by augusto-herrmann** [comment]
> Mas temos que colocar os links de assistirem o streaming

Os links do streaming serão colocados na página do evento cerca de meia hora antes do evento. Acho que não tem como ter um link com antecedência.

**Comment by augusto-herrmann** [comment]
Evento realizado.
